CREATE DATABASE EC4_CC1M;

USE EC4_CC1M;

CREATE TABLE IF NOT EXISTS ALUNOS (
    CPF_ALUNO INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DATA_NASC_ALUNO DATE NOT NULL,
    MODALIDADE_ALUNO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS RESPONSAVEL(
    CPF_RESPONSAVEL INT PRIMARY KEY,
    NOME_RESPONSAVEL VARCHAR(100) NOT NULL,
    CPF_ALUNO INT,
    CONSTRAINT FK_CPF_ALUNO_ FOREIGN KEY (CPF_ALUNO)
    REFERENCES ALUNOS(CPF_ALUNO)
);


CREATE TABLE IF NOT EXISTS MODALIDADES(
    ID_MODALIDADE INT PRIMARY KEY,
    NOME_MODALIDADE VARCHAR(100) NOT NULL,
    QNTD_ALUNOS_MODALIDADE INT NOT NULL,
    CPF_ALUNO INT,
    CONSTRAINT FK_CPF_ALUNO FOREIGN KEY (CPF_ALUNO)
    REFERENCES ALUNOS(CPF_ALUNO)
);

CREATE TABLE IF NOT EXISTS INSTRUTORES(
    ID_INSTRUTOR INT PRIMARY KEY,
    NOME_INSTRUTOR VARCHAR(100) NOT NULL,
    ID_MODALIDADE INT NOT NULL,
    CPF_ALUNO INT,
    CONSTRAINT FK_ID_MODALIDADE FOREIGN KEY (ID_MODALIDADE) 
    REFERENCES MODALIDADES(ID_MODALIDADE),
    CONSTRAINT FK_CPF FOREIGN KEY (CPF_ALUNO)
    REFERENCES ALUNOS(CPF_ALUNO)
);


CREATE TABLE IF NOT EXISTS PLANOS_DE_TREINAMENTO(
    ID_PLANO INT PRIMARY KEY,
    DESC_PLANO VARCHAR(100) NOT NULL,
    ID_INSTRUTOR INT NOT NULL,
    CPF_ALUNO INT,
    CONSTRAINT FK_ID_INSTRUTOR FOREIGN KEY (ID_INSTRUTOR)
    REFERENCES INSTRUTORES(ID_INSTRUTOR),
    CONSTRAINT FK_CPFALUNO FOREIGN KEY (CPF_ALUNO)
    REFERENCES ALUNOS(CPF_ALUNO)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
    ID_PAGAMENTO INT PRIMARY KEY,
    DATA_PAGAMENTO DATE NOT NULL,
    VALOR_PAGAMENTO DECIMAL(10,2) NOT NULL,
    STATUS_PAGAMENTO ENUM('PENDENTE', 'PAGO', 'REJEITADO') NOT NULL,
    CPF_ALUNO INT,
    CONSTRAINT FK_ALUNO FOREIGN KEY (CPF_ALUNO)
    REFERENCES ALUNOS(CPF_ALUNO)
);

CREATE TABLE IF NOT EXISTS ENDERECO(
    CEP_ENDERECO INT PRIMARY KEY,
    RUA_ENDERECO VARCHAR(100) NOT NULL,
    NUMERO_ENDERECO INT NOT NULL,
    BAIRRO_ENDERECO VARCHAR(100) NOT NULL,
    CIDADE_ENDERECO VARCHAR(100) NOT NULL,
    ESTADO_ENDERECO VARCHAR(100) NOT NULL,
    PAIS_ENDERECO VARCHAR(100) NOT NULL,
    CPF_ALUNO INT,
    CONSTRAINT FK_CPF_DOALUNO FOREIGN KEY (CPF_ALUNO)
    REFERENCES ALUNOS(CPF_ALUNO)
);

CREATE TABLE IF NOT EXISTS AULAS(
    ID_AULA INT PRIMARY KEY,
    DATA_AULA DATE NOT NULL,
    HORA_AULA TIME NOT NULL,
    CAPACIDADE_AULA INT NOT NULL,
    ID_INSTRUTOR INT NOT NULL,
    CPF_ALUNO INT,
    CONSTRAINT FK_IDINSTRUTOR FOREIGN KEY (ID_INSTRUTOR)
    REFERENCES INSTRUTORES(ID_INSTRUTOR),
    CONSTRAINT FK_CPF_DO_ALUNO FOREIGN KEY (CPF_ALUNO)
    REFERENCES ALUNOS(CPF_ALUNO)
);

CREATE TABLE IF NOT EXISTS ALUNOS_MODALIDADES(
    ALMD_ALUNO INT,
    ALMD_MODALIDADE INT,
    PRIMARY KEY (ALMD_ALUNO, ALMD_MODALIDADE),
    CONSTRAINT FK_ALMD_ALUNO FOREIGN KEY (ALMD_ALUNO)
    REFERENCES ALUNOS(CPF_ALUNO),
    CONSTRAINT FK_ALMD_MODALIDADE FOREIGN KEY (ALMD_MODALIDADE)
    REFERENCES MODALIDADES(ID_MODALIDADE)
);


ALTER TABLE ALUNOS
    ADD COLUMN email VARCHAR(100) NOT NULL;
ALTER TABLE ALUNOS
    MODIFY COLUMN email VARCHAR(150) NOT NULL;
ALTER TABLE ALUNOS
    CHANGE email EMAIL_ALUNO VARCHAR(150) NOT NULL;
ALTER TABLE ALUNOS    
    DROP COLUMN EMAIL_ALUNO;

ALTER TABLE RESPONSAVEL
    ADD COLUMN email VARCHAR(100) NOT NULL;
ALTER TABLE RESPONSAVEL
    MODIFY COLUMN email VARCHAR(150) NOT NULL;
ALTER TABLE RESPONSAVEL
    CHANGE email EMAIL_RESPONSAVEL VARCHAR(150) NOT NULL;
ALTER TABLE RESPONSAVEL
    DROP COLUMN EMAIL_RESPONSAVEL;

ALTER TABLE INSTRUTORES
    ADD COLUMN email VARCHAR(100) NOT NULL;
ALTER TABLE INSTRUTORES
    MODIFY COLUMN email VARCHAR(150) NOT NULL;
ALTER TABLE INSTRUTORES
    CHANGE COLUMN email EMAIL_INST VARCHAR(150) NOT NULL;
ALTER TABLE INSTRUTORES
    DROP COLUMN EMAIL_INST;

ALTER TABLE MODALIDADES
    ADD COLUMN tipo VARCHAR(100) NOT NULL;
ALTER TABLE MODALIDADES    
    MODIFY COLUMN tipo VARCHAR(150) NOT NULL;
ALTER TABLE MODALIDADES    
    CHANGE tipo TIPO_MODALIDADE VARCHAR(150) NOT NULL;
ALTER TABLE MODALIDADES    
    DROP COLUMN TIPO_MODALIDADE;

ALTER TABLE PLANOS_DE_TREINAMENTO
    ADD COLUMN tipo VARCHAR(100) NOT NULL;
ALTER TABLE PLANOS_DE_TREINAMENTO    
    MODIFY COLUMN tipo VARCHAR(150) NOT NULL;
ALTER TABLE PLANOS_DE_TREINAMENTO
    CHANGE TIPO TIPO_PLANO VARCHAR(150) NOT NULL;
ALTER TABLE PLANOS_DE_TREINAMENTO    
    DROP COLUMN TIPO_PLANO;

ALTER TABLE PAGAMENTOS
    ADD COLUMN tipo VARCHAR(100) NOT NULL;
ALTER TABLE PAGAMENTOS    
    MODIFY COLUMN tipo VARCHAR(150) NOT NULL;
ALTER TABLE PAGAMENTOS
    CHANGE tipo TIPO_PAGAMENTO VARCHAR(150) NOT NULL;
ALTER TABLE PAGAMENTOS
    DROP COLUMN TIPO_PAGAMENTO;

ALTER TABLE ENDERECO
    ADD COLUMN complemento VARCHAR(100) NOT NULL;
ALTER TABLE ENDERECO    
    MODIFY COLUMN complemento VARCHAR(150) NOT NULL;
ALTER TABLE ENDERECO    
    CHANGE complemento COMPLEMENTO_ENDERECO VARCHAR(150) NOT NULL;
ALTER TABLE ENDERECO    
    DROP COLUMN COMPLEMENTO_ENDERECO;

ALTER TABLE AULAS
    ADD COLUMN num VARCHAR(100) NOT NULL;
ALTER TABLE AULAS    
    MODIFY COLUMN num VARCHAR(150) NOT NULL;
ALTER TABLE AULAS    
    CHANGE num NUMERO_DE_AULA VARCHAR(150) NOT NULL;
ALTER TABLE AULAS    
    DROP COLUMN NUMERO_DE_AULA;

ALTER TABLE ALUNOS_MODALIDADES
    ADD COLUMN num VARCHAR(100) NOT NULL;
ALTER TABLE ALUNOS_MODALIDADES    
    MODIFY COLUMN num VARCHAR(150) NOT NULL;
ALTER TABLE ALUNOS_MODALIDADES    
    CHANGE num NUMERO_DE_ALUNO VARCHAR(150) NOT NULL;
ALTER TABLE ALUNOS_MODALIDADES    
    DROP COLUMN NUMERO_DE_ALUNO;

DROP TABLE RESPONSAVEL;