CREATE DATABASE EC1_CC1M;

USE EC1_CC1M;

CREATE TABLE IF NOT EXISTS FORNECEDORES(
    FORNEC_COD INT PRIMARY KEY,
    FORNEC_RUA VARCHAR(45) NOT NULL,
    FORNEC_NUMRUA INT,
    FORNEC_BAIRRO VARCHAR(45) NOT NULL,
    FORNEC_CIDADE VARCHAR(45) NOT NULL,
    FORNEC_ESTADO VARCHAR(45) NOT NULL,
    FORNEC_PAIS VARCHAR(45) NOT NULL,
    FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
    FORNEC_TELEFONE VARCHAR(15) NOT NULL,
    FORNEC_CONTATO TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS FILIAIS(
    FILIAL_COD INT PRIMARY KEY,
    FILIAL_RUA VARCHAR(45) NOT NULL,
    FILIAL_NUMRUA INT,
    FILIAL_BAIRRO VARCHAR(50) NOT NULL,
    FILIAL_CIDADE VARCHAR(50) NOT NULL,
    FILIAL_ESTADO VARCHAR(50) NOT NULL,
    FILIAL_PAIS VARCHAR(50) NOT NULL,
    FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
    FILIAL_CAPACIDADE TEXT NOT NULL
); 

CREATE TABLE IF NOT EXISTS PRODUTOS(
    PROD_COD INT PRIMARY KEY,
    PROD_DESCRICAO TEXT NOT NULL,
    PROD_ESPECTEC TEXT NOT NULL,
    PROD_QUANT DECIMAL(10,3) NOT NULL,
    PROD_PRECIUNIT DECIMAL(10,2) NOT NULL,
    PROD_UNIDMEDIA VARCHAR(10) NOT NULL,
    PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTES(
    CLI_COD INT PRIMARY KEY,
    CLI_RUA VARCHAR(50) NOT NULL,
    CLI_NUMRUA INT,
    CLI_BAIRRO VARCHAR(50) NOT NULL,
    CLI_CIDADE VARCHAR(50) NOT NULL,
    CLI_ESTADO VARCHAR(50) NOT NULL,
    CLI_PAIS VARCHAR(50) NOT NULL,
    CLI_CODPOSTAL VARCHAR(10) NOT NULL,
    CLI_TELEFONE VARCHAR(15) NOT NULL
);


DROP TABLE CLIENTES;

CREATE TABLE IF NOT EXISTS PEDIDOS(
    PED_COD INT PRIMARY KEY,
    PED_DATA DATE NOT NULL,
    PED_HORA TIME NOT NULL,
    PED_PREVISAO DATE NOT NULL,
    PED_STATUS ENUM('PENDENTE', 'CONCLUIDO', 'EM ESPERA') NOT NULL,
    PED_FORNECEDOR INT NOT NULL,  
    CONSTRAINT FK_FORNECEDOR FOREIGN KEY(PED_FORNECEDOR)
    REFERENCES FORNECEDORES(FORNEC_COD) 
);

CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
    RECEB_DATA DATE NOT NULL,
    RECEB_HORA TIME NOT NULL,
    RECEB_QUANT_PROD DECIMAL(10,3),
    RECEB_CONDICAO TEXT NOT NULL,
    RECEB_PEDIDOS INT PRIMARY KEY,
    CONSTRAINT FK_PEDIDOS FOREIGN KEY(RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO)
);

CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
    PDPR_PEDIDOS INT,
    PDPR_PRODUTOS INT,
    PRIMARY KEY (PDPR_PEDIDOS, PDPR_PRODUTOS),
    PDPR_QUANT DECIMAL(10,3) NOT NULL,
    CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS) 
    REFERENCES PEDIDOS(PED_CODIGO),
    CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY(PDPR_PRODUTOS) 
    REFERENCES PRODUTOS(PROD_COD)
);

CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
    FLPR_FILIAL INT,
    FLPR_PRODUTOS INT,
    PRIMARY KEY (FLPR_FILIAL, FLPR_PRODUTOS),
    FLPR_QUANT DECIMAL(10,3) NOT NULL,
    CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY(FLPR_FILIAL) 
    REFERENCES FILIAIS(FILIAL_COD),
    CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY(FLPR_PRODUTOS) 
    REFERENCES PRODUTOS(PROD_COD)
);


CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
    FRPR_FORNECEDOR INT,
    FRPR_PRODUTOS INT,
    PRIMARY KEY (FRPR_FORNECEDOR, FRPR_PRODUTOS),
    CONSTRAINT FRPR_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR)
    REFERENCES FORNECEDORES(FORNEC_COD),
    CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS)
    REFERENCES PRODUTOS(PROD_COD)
);

ALTER TABLE FORNECEDORES    
    ADD email VARCHAR(100);
ALTER TABLE FORNECEDORES
    MODIFY COLUMN email VARCHAR(150);
ALTER TABLE FORNECEDORES
    CHANGE COLUMN email EMAIL_FORNEC VARCHAR(150);
ALTER TABLE FORNECEDORES
    DROP COLUMN EMAIL_FORNEC;


ALTER TABLE FILIAIS
    ADD email VARCHAR(100);
ALTER TABLE FILIAIS
    MODIFY COLUMN email VARCHAR(150);
ALTER TABLE FILIAIS
    CHANGE COLUMN email EMAIL_FILIAL VARCHAR(150);
ALTER TABLE FILIAIS
    DROP COLUMN EMAIL_FILIAL;


ALTER TABLE PRODUTOS
    ADD medida VARCHAR(100);
ALTER TABLE PRODUTOS
    MODIFY COLUMN medida VARCHAR(150);
ALTER TABLE PRODUTOS
    CHANGE COLUMN medida MEDIDA_PROD VARCHAR(150);
ALTER TABLE PRODUTOS
    DROP COLUMN MEDIDA_PROD;


ALTER TABLE CLIENTES
    ADD email VARCHAR(100);
ALTER TABLE CLIENTES
    MODIFY COLUMN email VARCHAR(150);
ALTER TABLE CLIENTES
    CHANGE COLUMN email EMAIL_CLI VARCHAR(150);
ALTER TABLE CLIENTES
    DROP COLUMN EMAIL_CLI;


ALTER TABLE PEDIDOS
    ADD quantidade DECIMAL(10,2);
ALTER TABLE PEDIDOS
    MODIFY COLUMN quantidade DECIMAL(10,3);
ALTER TABLE PEDIDOS
    CHANGE COLUMN quantidade QUANTIDADE_PED DECIMAL(10,3);
ALTER TABLE PEDIDOS
    DROP COLUMN QUANTIDADE_PED;


ALTER TABLE RECEBIMENTOS
    ADD localizacao VARCHAR(100);
ALTER TABLE RECEBIMENTOS
    MODIFY COLUMN localizacao VARCHAR(150);
ALTER TABLE RECEBIMENTOS
    CHANGE COLUMN localizacao LOCALIZACAO_DE_REC VARCHAR(150);
ALTER TABLE RECEBIMENTOS
    DROP COLUMN LOCALIZACAO_DE_REC;


ALTER TABLE PEDIDOS_PRODUTOS
    ADD quantidade DECIMAL(10,2);
ALTER TABLE PEDIDOS_PRODUTOS
    MODIFY COLUMN quantidade DECIMAL(10,3);
ALTER TABLE PEDIDOS_PRODUTOS
    CHANGE COLUMN quantidade QUANTIDADE_PDPR DECIMAL(10,3);
ALTER TABLE PEDIDOS_PRODUTOS
    DROP COLUMN QUANTIDADE_PDPR;

ALTER TABLE FILIAIS_PRODUTOS
    ADD quantidade DECIMAL(10,2);
ALTER TABLE FILIAIS_PRODUTOS
    MODIFY COLUMN quantidade DECIMAL(10,3);
ALTER TABLE FILIAIS_PRODUTOS
    CHANGE COLUMN quantidade QUANTIDADE_FLPR DECIMAL(10,3);
ALTER TABLE FILIAIS_PRODUTOS
    DROP COLUMN QUANTIDADE_FLPR;

ALTER TABLE FORNECEDORES_PRODUTOS
    ADD quantidade DECIMAL(10,2);
ALTER TABLE FORNECEDORES_PRODUTOS
    MODIFY COLUMN quantidade DECIMAL(10,3);
ALTER TABLE FORNECEDORES_PRODUTOS
    CHANGE COLUMN quantidade QUANTIDADE_FRPR DECIMAL(10,3);
ALTER TABLE FORNECEDORES_PRODUTOS
    DROP COLUMN QUANTIDADE_FRPR;
