CREATE DATABASE EC5_CC1M;

USE EC5_CC1M;

CREATE TABLE IF NOT EXISTS CLIENTES(
    CPF_CLIENTE VARCHAR(11) PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    STTS_FIDELIDADE_CLIENTE BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
    CPF_FUNCIONARIO VARCHAR(11) PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CARGO_FUNCIONARIO VARCHAR(100) NOT NULL,
    SALARIO_FUNCIONARIO DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
    CNPJ_FORNECEDOR VARCHAR(14) PRIMARY KEY,
    NOME_FORNECEDOR VARCHAR(100) NOT NULL,
    ID_PRODUTO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
    ID_PRODUTO INT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    VALOR_PRODUTO DECIMAL(10,2) NOT NULL,
    QNTD_ESTOQUE_PRODUTO INT NOT NULL,
    INFO_PRODUTO VARCHAR(100) NOT NULL,
    CNPJ_FORNECEDOR VARCHAR(14) NOT NULL,
    CONSTRAINT FK_FORNECEDOR FOREIGN KEY (CNPJ_FORNECEDOR) 
    REFERENCES FORNECEDORES(CNPJ_FORNECEDOR)
);


CREATE TABLE IF NOT EXISTS VENDAS(
    ID_VENDA INT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL,
    CPF_CLIENTE VARCHAR(11) NOT NULL,
    ID_PAGAMENTO INT NOT NULL,
    DESC_VENDA VARCHAR(255) NOT NULL,
    FORMA_PAGAMENTO_VENDA VARCHAR(100) NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    DATA_VENDA DATE NOT NULL,
    CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO)
    REFERENCES PRODUTOS(ID_PRODUTO),
    CONSTRAINT FK_CLIENTE FOREIGN KEY (CPF_CLIENTE)
    REFERENCES CLIENTES(CPF_CLIENTE)
);

ALTER TABLE CLIENTES
    ADD COLUMN EMAIL VARCHAR(100) NOT NULL;
ALTER TABLE CLIENTES
    MODIFY COLUMN EMAIL VARCHAR(150) NOT NULL;
ALTER TABLE CLIENTES
    CHANGE COLUMN EMAIL EMAIL_CLIENTE VARCHAR(150) NOT NULL;
ALTER TABLE CLIENTES
    DROP COLUMN EMAIL_CLIENTE;

ALTER TABLE FUNCIONARIO
    ADD COLUMN EMAIL VARCHAR(100) NOT NULL;
ALTER TABLE FUNCIONARIO
    MODIFY COLUMN EMAIL VARCHAR(150) NOT NULL;
ALTER TABLE FUNCIONARIO
    CHANGE COLUMN EMAIL EMAIL_FUNCIONARIO VARCHAR(150) NOT NULL;
ALTER TABLE FUNCIONARIO
    DROP COLUMN EMAIL_FUNCIONARIO;

ALTER TABLE PRODUTOS
    ADD COLUMN DESCONTO DECIMAL(10,2) NOT NULL;
ALTER TABLE PRODUTOS
    MODIFY COLUMN DESCONTO DECIMAL(10,3) NOT NULL;
ALTER TABLE PRODUTOS
    CHANGE COLUMN DESCONTO DESCONTO_PRODUTO DECIMAL(10,3) NOT NULL;
ALTER TABLE PRODUTOS
    DROP COLUMN DESCONTO_PRODUTO;

ALTER TABLE FORNECEDORES
    ADD COLUMN EMAIL VARCHAR(100) NOT NULL;
ALTER TABLE FORNECEDORES
    MODIFY COLUMN EMAIL VARCHAR(150) NOT NULL;
ALTER TABLE FORNECEDORES
    CHANGE COLUMN EMAIL EMAIL_FORNECEDOR VARCHAR(150) NOT NULL;
ALTER TABLE FORNECEDORES
    DROP COLUMN EMAIL_FORNECEDOR;

ALTER TABLE VENDAS
    ADD COLUMN DESCONTO DECIMAL(10,2) NOT NULL;
ALTER TABLE VENDAS
    MODIFY COLUMN DESCONTO DECIMAL(10,3) NOT NULL;
ALTER TABLE VENDAS
    CHANGE COLUMN DESCONTO DESCONTO_VENDA DECIMAL(10,3) NOT NULL;
ALTER TABLE VENDAS
    DROP COLUMN DESCONTO_VENDA;

DROP TABLE FUNCIONARIO;
