CREATE DATABASE EC2_CC1M;

USE EC2_CC1M;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
    CPF_PASSAGEIROS INT PRIMARY KEY,
    NOME_PASSAGEIROS VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS AERONAVES(
    ID_AERONAVES INT PRIMARY KEY,
    MODELO_AERONAVES VARCHAR(50),
    CAPACIDADE_AERONAVES INT,
    VOOS_AERONAVES INT
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
    CPF_FUNCIONARIOS INT PRIMARY KEY,
    NOME_FUNCIONARIOS VARCHAR(50),
    CARGO_FUNCIONARIOS VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS RESERVAS(
    ID_RESERVAS INT PRIMARY KEY,
    CPF_PASSAGEIROS INT NOT NULL,
    ID_VOO INT NOT NULL,
    CONSTRAINT FK_PASSAGEIROS FOREIGN KEY (CPF_PASSAGEIROS)
    REFERENCES PASSAGEIROS(CPF_PASSAGEIROS)
);

CREATE TABLE IF NOT EXISTS VOOS(
    ID_VOO INT PRIMARY KEY,
    DATA_VOOS DATE,
    HORA_VOOS TIME,
    ORIGEM_VOOS VARCHAR(50),
    DESTINO_VOOS VARCHAR(50),
    ID_RESERVAS INT NOT NULL,
    CONSTRAINT FK_RESERVAS FOREIGN KEY (ID_RESERVAS)
    REFERENCES RESERVAS(ID_RESERVAS)
);

CREATE TABLE IF NOT EXISTS AEROPORTOS(
    ID_AEROPORTO INT PRIMARY KEY,
    NOME_AEROPORTO VARCHAR(50),
    CIDADE_AEROPORTO VARCHAR(50),
    ESTADO_AEROPORTO VARCHAR(50),
    PAIS_AEROPORTO VARCHAR(50),
    ID_AERONAVES INT NOT NULL,
    CONSTRAINT FK_AERONAVES FOREIGN KEY (ID_AERONAVES)
    REFERENCES AERONAVES(ID_AERONAVES)
);

CREATE TABLE IF NOT EXISTS ENDERECO(
    RUA_ENDERECO VARCHAR(50),
    NUMRUA_ENDERECO INT,
    BAIRRO_ENDERECO VARCHAR(50),
    CIDADE_ENDERECO VARCHAR(50),
    ESTADO_ENDERECO VARCHAR(50),
    PAIS_ENDERECO VARCHAR(50),
    CEP_ENDERECO VARCHAR(10),
    CPF_PASSAGEIROS INT NOT NULL,
    CONSTRAINT FK_CPF FOREIGN KEY (CPF_PASSAGEIROS)
    REFERENCES PASSAGEIROS(CPF_PASSAGEIROS)
);

CREATE TABLE IF NOT EXISTS TELEFONE(
    NUM_TEL VARCHAR(15),
    CPF_PASSAGEIROS INT NOT NULL,
    CONSTRAINT FK_CPF_PASSAGEIROS FOREIGN KEY (CPF_PASSAGEIROS)
    REFERENCES PASSAGEIROS(CPF_PASSAGEIROS)
);

CREATE TABLE IF NOT EXISTS BAGAGEM(
    ID_BAGAGEM INT PRIMARY KEY
);

DROP TABLE IF EXISTS BAGAGEM;


ALTER TABLE PASSAGEIROS
    ADD COLUMN email VARCHAR(50);
ALTER TABLE PASSAGEIROS
    MODIFY COLUMN email VARCHAR(100) NOT NULL;
ALTER TABLE PASSAGEIROS
    CHANGE COLUMN email EMAIL_PASSAGEIROS VARCHAR(100) NOT NULL;
ALTER TABLE PASSAGEIROS
    DROP COLUMN EMAIL_PASSAGEIROS;



ALTER TABLE AERONAVES
    ADD COLUMN ANO_FABRICACAO INT;
ALTER TABLE AERONAVES
    MODIFY COLUMN ANO_FABRICACAO INT NOT NULL;
ALTER TABLE AERONAVES
    CHANGE COLUMN ANO_FABRICACAO ANO_FABRICACAO_AERONAVES INT NOT NULL;
ALTER TABLE AERONAVES
    DROP COLUMN ANO_FABRICACAO_AERONAVES;


ALTER TABLE FUNCIONARIOS
    ADD COLUMN SALARIO DECIMAL(10,2);
ALTER TABLE FUNCIONARIOS
    MODIFY COLUMN SALARIO DECIMAL(10,2) NOT NULL;
ALTER TABLE FUNCIONARIOS
    CHANGE COLUMN SALARIO SALARIO_FUNCIONARIOS DECIMAL(10,2) NOT NULL;
ALTER TABLE FUNCIONARIOS
    DROP COLUMN SALARIO_FUNCIONARIOS;


ALTER TABLE VOOS
    ADD COLUMN tempo INT;
ALTER TABLE VOOS
    MODIFY COLUMN tempo INT NOT NULL;
ALTER TABLE VOOS   
    CHANGE COLUMN tempo TEMPO_DE_VOO INT NOT NULL;
ALTER TABLE VOOS    
    DROP COLUMN TEMPO_DE_VOO;


ALTER TABLE AEROPORTOS
    ADD COLUMN wifi INT;
ALTER TABLE AEROPORTOS    
    MODIFY COLUMN wifi INT NOT NULL;
ALTER TABLE AEROPORTOS    
    CHANGE COLUMN wifi WIFI_AEROPORTOS INT NOT NULL;
ALTER TABLE AEROPORTOS    
    DROP COLUMN WIFI_AEROPORTOS;


ALTER TABLE RESERVAS
    ADD COLUMN bagagem INT;
ALTER TABLE RESERVAS   
    MODIFY COLUMN bagagem INT NOT NULL;
ALTER TABLE RESERVAS    
    CHANGE COLUMN bagagem QNTD_BAGAGEM_RESERVAS INT NOT NULL;
ALTER TABLE RESERVAS    
    DROP COLUMN QNTD_BAGAGEM_RESERVAS;

ALTER TABLE ENDERECO
    ADD COLUMN COMPLEMENTO VARCHAR(50);
ALTER TABLE ENDERECO    
    MODIFY COLUMN COMPLEMENTO VARCHAR(50) NOT NULL;
ALTER TABLE ENDERECO   
    CHANGE COLUMN COMPLEMENTO COMPLEMENTO_ENDERECO VARCHAR(50) NOT NULL;
ALTER TABLE ENDERECO  
    DROP COLUMN COMPLEMENTO_ENDERECO;

ALTER TABLE TELEFONE
    ADD COLUMN ddd VARCHAR(15);
ALTER TABLE TELEFONE
    MODIFY COLUMN ddd VARCHAR(15) NOT NULL;
ALTER TABLE TELEFONE    
    CHANGE COLUMN ddd DDD_TELEFONE VARCHAR(15) NOT NULL;
ALTER TABLE TELEFONE    
    DROP COLUMN DDD_TELEFONE;