CREATE DATABASE EC3_CC1M;

USE EC3_CC1M;

CREATE TABLE IF NOT EXISTS CLIENTES(
    COD_CLIENTE INT PRIMARY KEY,
    CNPJ VARCHAR(14) NOT NULL,
    RAZS VARCHAR(100) NOT NULL,
    RAM_ATV VARCHAR(100) NOT NULL,
    DATA_CAD DATE NOT NULL,
    PSS_CONTATO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPREGADOS(
    COD_MATRICULA INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CARGO VARCHAR(100) NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    DATA_ADS DATE NOT NULL,
    QUALI VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
    CNPJ_FORNECEDOR VARCHAR(14) PRIMARY KEY,
    RAZS_FORNECEDOR VARCHAR(100) NOT NULL,
    PSS_CTT_FORNECEDOR VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TELEFONES(
    COD_TELEFONE INT PRIMARY KEY,
    NUMERO VARCHAR(11) NOT NULL,
    COD_CLIENTE INT NOT NULL,
    COD_MATRICULA INT NOT NULL,
    CNPJ_FORNECEDOR VARCHAR(14) NOT NULL,
    CONSTRAINT FK_CODCLIENTE FOREIGN KEY (COD_CLIENTE)
    REFERENCES CLIENTES(COD_CLIENTE),
    CONSTRAINT FK_CODMATRICULA FOREIGN KEY (COD_MATRICULA)
    REFERENCES EMPREGADOS(COD_MATRICULA),
    CONSTRAINT FK_CNPJF FOREIGN KEY (CNPJ_FORNECEDOR)
    REFERENCES FORNECEDORES(CNPJ_FORNECEDOR)
);


CREATE TABLE IF NOT EXISTS ENDERECOS(
    COD_ENDERECO INT PRIMARY KEY,
    NUMERO INT NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    LOGRADOURO VARCHAR(100) NOT NULL,
    COMPLEMENTO VARCHAR(100) NOT NULL,
    COD_CLIENTE INT NOT NULL,
    COD_MATRICULA INT NOT NULL,
    CNPJ_FORNECEDOR VARCHAR(14) NOT NULL,
    CONSTRAINT FK_COD_CLIENTE FOREIGN KEY (COD_CLIENTE)
    REFERENCES CLIENTES(COD_CLIENTE),
    CONSTRAINT FK_COD_MATRICULA FOREIGN KEY (COD_MATRICULA)
    REFERENCES EMPREGADOS(COD_MATRICULA),
    CONSTRAINT FK_CNPJ FOREIGN KEY (CNPJ_FORNECEDOR)
    REFERENCES FORNECEDORES(CNPJ_FORNECEDOR)
);

CREATE TABLE IF NOT EXISTS TIPO_ENDERECO(
    NOME_TIPO VARCHAR(100) PRIMARY KEY,
    COD_ENDERECO INT NOT NULL,
    CONSTRAINT FK_COD_ENDERECO FOREIGN KEY (COD_ENDERECO)
    REFERENCES ENDERECOS(COD_ENDERECO)
);

CREATE TABLE IF NOT EXISTS MAQUINAS(
    COD_MAQUINA INT PRIMARY KEY,
    TEMP_VIDA TIME NOT NULL,
    DATA_BUY DATE NOT NULL,
    DATA_GARANTIA DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS RE(
    COD_RECURSO INT PRIMARY KEY,
    QNTD_NEED INT NOT NULL,
    UNID VARCHAR(100) NOT NULL,
    TEMPO_USO TIME NOT NULL,
    HMO TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS RM(
    DATA_RM DATE NOT NULL,
    DESC_RM VARCHAR(100) NOT NULL,
    COD_MAQUINA INT NOT NULL,
    CONSTRAINT FK_COD_MAQUINA FOREIGN KEY (COD_MAQUINA)
    REFERENCES MAQUINAS(COD_MAQUINA)
);

CREATE TABLE IF NOT EXISTS RS(
    COD_SUPRIMENTO INT PRIMARY KEY,
    QNTD_SUPRIMENTO INT NOT NULL,
    DATE_NEED DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
    COD_PRODUTO INT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    TEMPO_FAB DECIMAL(10,2) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    H_MAO_OBRA TIME NOT NULL,
    COD_RECURSO INT NOT NULL,
    COD_SUPRIMENTO INT NOT NULL,
    COD_MAQUINA INT NOT NULL,
    CONSTRAINT FK_COD_RECURSO FOREIGN KEY (COD_RECURSO)
    REFERENCES RE(COD_RECURSO),
    CONSTRAINT FK_COD_SUPRIMENTO FOREIGN KEY (COD_SUPRIMENTO)
    REFERENCES RS(COD_SUPRIMENTO),
    CONSTRAINT FK_CODMAQUINA FOREIGN KEY (COD_MAQUINA)
    REFERENCES MAQUINAS(COD_MAQUINA)
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS(
    COD_ENCOMENDA INT PRIMARY KEY,
    DATA_INCLUSAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    VALOR_LIQUIDO DECIMAL(10,2) NOT NULL,
    VALOR_DESCONTO DECIMAL(10,2) NOT NULL,
    QNTD_PARCELAS INT NOT NULL,
    FORMA_PAGAMENTO VARCHAR(100) NOT NULL,
    COD_PRODUTO INT NOT NULL,
    CONSTRAINT FK_COD_PRODUTO FOREIGN KEY (COD_PRODUTO)
    REFERENCES PRODUTOS(COD_PRODUTO)
);

CREATE TABLE IF NOT EXISTS CARACTERISTICAS_PRODUTOS(
    DESENHO_PRODUTO VARCHAR(100),
    COR VARCHAR(30),
    PESO DECIMAL(10,2),
    DIMENSOES VARCHAR(100),
    COD_PRODUTO INT NOT NULL,
    CONSTRAINT FK_CODPRODUTO FOREIGN KEY (COD_PRODUTO)
    REFERENCES PRODUTOS(COD_PRODUTO)
);


CREATE TABLE IF NOT EXISTS COMPONENTES(
    COD_COMPONENTE INT PRIMARY KEY,
    NOME_COMPONENTE VARCHAR(100) NOT NULL,
    QNTD_ESTQ INT NOT NULL,
    PRECO_UNIT DECIMAL(10,2) NOT NULL,
    UNIDADE VARCHAR(100) NOT NULL,
    CNPJ_FORNECEDOR VARCHAR(14) NOT NULL,
    CONSTRAINT FK_CNPJ_FORNECEDOR FOREIGN KEY (CNPJ_FORNECEDOR)
    REFERENCES FORNECEDORES(CNPJ_FORNECEDOR)
);

CREATE TABLE IF NOT EXISTS TIPOS_COMPONENTE(
    NOME VARCHAR(100) PRIMARY KEY,
    TIPO VARCHAR(100) NOT NULL,
    COD_COMPONENTE INT NOT NULL,
    CONSTRAINT FK_COD_COMPONENTE FOREIGN KEY (COD_COMPONENTE)
    REFERENCES COMPONENTES(COD_COMPONENTE)
);

CREATE TABLE IF NOT EXISTS PIX(
    CHAVE_PIX VARCHAR(100) PRIMARY KEY
);

ALTER TABLE CLIENTES 
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE CLIENTES
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE CLIENTES
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE CLIENTES
    DROP COLUMN CHAVE_PIX;

ALTER TABLE EMPREGADOS
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE EMPREGADOS
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE EMPREGADOS
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE EMPREGADOS
    DROP COLUMN CHAVE_PIX;

ALTER TABLE FORNECEDORES
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE FORNECEDORES
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE FORNECEDORES
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE FORNECEDORES
    DROP COLUMN CHAVE_PIX;

ALTER TABLE TELEFONES
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE TELEFONES
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE TELEFONES
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE TELEFONES
    DROP COLUMN CHAVE_PIX;

ALTER TABLE ENDERECOS
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE ENDERECOS
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE ENDERECOS
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE ENDERECOS
    DROP COLUMN CHAVE_PIX;

ALTER TABLE TIPO_ENDERECO
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE TIPO_ENDERECO
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE TIPO_ENDERECO
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE TIPO_ENDERECO
    DROP COLUMN CHAVE_PIX;

ALTER TABLE MAQUINAS
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE MAQUINAS
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE MAQUINAS
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE MAQUINAS
    DROP COLUMN CHAVE_PIX;

ALTER TABLE RE
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE RE
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE RE
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE RE
    DROP COLUMN CHAVE_PIX;

ALTER TABLE RM
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE RM
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE RM
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE RM
    DROP COLUMN CHAVE_PIX;

ALTER TABLE RS
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE RS
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE RS
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE RS
    DROP COLUMN CHAVE_PIX;

ALTER TABLE PRODUTOS
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE PRODUTOS
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE PRODUTOS
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE PRODUTOS
    DROP COLUMN CHAVE_PIX;

ALTER TABLE ENCOMENDAS
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE ENCOMENDAS
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE ENCOMENDAS
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE ENCOMENDAS
    DROP COLUMN CHAVE_PIX;

ALTER TABLE CARATERISTICAS_PRODUTOS
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE CARATERISTICAS_PRODUTOS
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE CARATERISTICAS_PRODUTOS
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE CARATERISTICAS_PRODUTOS
    DROP COLUMN CHAVE_PIX;

ALTER TABLE COMPONENTES
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE COMPONENTES
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE COMPONENTES
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE COMPONENTES
    DROP COLUMN CHAVE_PIX;

ALTER TABLE TIPOS_COMPONENTE
    ADD COLUMN CHAVE VARCHAR(100);
ALTER TABLE TIPOS_COMPONENTE
    MODIFY COLUMN CHAVE VARCHAR(100) NOT NULL;
ALTER TABLE TIPOS_COMPONENTE
    CHANGE COLUMN CHAVE CHAVE_PIX VARCHAR(100) NOT NULL;
ALTER TABLE TIPOS_COMPONENTE
    DROP COLUMN CHAVE_PIX;

DROP TABLE PIX;
